name: Build and publish Python package to PyPI

on:
  push:
    branches:
      - main

env:
  PYPI_PROJECT_NAME: moderate-matrix-profile
  PYTHON_VERSION: "3.11"
  POETRY_VERSION: "1.8.3"

jobs:
  build-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ env.PYPI_PROJECT_NAME }}
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Poetry install & build
        run: |
          poetry install
          poetry build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          skip-existing: true
          packages-dir: dist/
          verbose: true
